# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  one_line_install:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - run:
          command: |
            curl -LsS https://raw.githubusercontent.com/GetPoplog/Seed/main/GetPoplog.sh | sh
  build_tree:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Get system info
          command: |
            uname -a
            ldd --version
      - run:
          name: Install dependencies
          command: make jumpstart-ubuntu
      - run:
          name: Build poplog_base file-tree
          command: make build
      - run:
          name: Install Poplog from its file-tree
          command: sudo make install
      - run:
          name: Export file-tree as tarball
          command: make _build/poplog.tar.gz
      - store_artifacts:
          path: _build/poplog.tar.gz
          destination: poplog.tar.gz
      - persist_to_workspace:
          root: _build
          paths:
            - Done.proxy
            - poplog.tar.gz
  build_deb:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Get system info
          command: |
            uname -a
            ldd --version
      - run:
          command: |
            sudo apt update
            sudo apt install -y make curl
      - attach_workspace:
          at: _build
      - run:
          command: |
            make builddeb
      - store_artifacts:
          path: _build/poplog_16.1-1_amd64.deb
          destination: poplog_16.1-1_amd64.deb
  build_rpm:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Get system info
          command: |
            uname -a
            ldd --version
      - attach_workspace:
          at: _build
      - run:
          command: |
            sudo apt update
            sudo apt install -y make alien curl
      - run:
          command: |
            make buildrpm
      - store_artifacts:
          path: _build/poplog-16.1-1.x86_64.rpm
          destination: poplog-16.1-1.x86_64.rpm
  build_appimage:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Get system info
          command: |
            uname -a
            ldd --version
      - attach_workspace:
          at: _build
      - run:
          command: |
            sudo apt update
            sudo apt install -y make curl libncurses5 libncurses5-dev
      - run:
          command:
            make buildappimage
      - store_artifacts:
          path: _build/Poplog-x86_64.AppImage
          destination: Poplog-x86_64.AppImage
  build_snap-machine:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Get system info
          command: |
            uname -a
            ldd --version
      - run:
          name: Get system info
          command: uname -a
      - attach_workspace:
          at: _build
      - run:
          command: |
            sudo apt update
            sudo apt install snapcraft
      - run:
          command: |
            make buildsnapcraftready
            cd _build/dotsnap; snapcraft --destructive-mode
      - store_artifacts:
          path: _build/dotsnap/poplog_16.0.1_amd64.snap
          destination: poplog_16.0.1_amd64.snap
  build_snap-docker:
    docker:
      - image: cibuilds/snapcraft:core20
    steps:
      - checkout
      - run:
          name: Get system info
          command: |
            uname -a
            ldd --version
      - run:
          name: Get system info
          command: uname -a
      - attach_workspace:
          at: _build
      - run:
          command: |
            sudo apt update
            sudo apt install make 
      - run:
          command: |
            make buildsnapcraftready
            cd _build/dotsnap; snapcraft
      - store_artifacts:
          path: _build/dotsnap/poplog_16.0.1_amd64.snap
          destination: poplog_16.0.1_amd64.snap

workflows:
  version: 2
  mainflow:
    jobs:
      - one_line_install
      - build_tree
      - build_deb:
          requires:
            - build_tree
      - build_rpm:
          requires:
            - build_tree
      - build_appimage:
          requires:
            - build_tree
      - build_snap-machine:
          requires:
            - build_tree
      - build_snap-docker:
          requires:
            - build_tree
