# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  one_line_install:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - run:
          command: |
            curl -LsS https://raw.githubusercontent.com/GetPoplog/Seed/main/GetPoplog.sh | sh
  build_tree:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Get system info
          command: uname -a
      - run:
          command: |
            make jumpstart-ubuntu
            make build
            sudo make install
            make _build/poplog.tar.gz
      - store_artifacts:
          path: _build/poplog.tar.gz
          destination: poplog.tar.gz
      - persist_to_workspace:
          root: _build
          paths:
            - Done.proxy
            - poplog.tar.gz
  build_deb:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          command: |
            sudo apt update
            sudo apt install -y make curl
      - attach_workspace:
          at: _build
      - run:
          command: |
            make builddeb
      - store_artifacts:
          path: _build/poplog_16.1-1_amd64.deb
          destination: poplog_16.1-1_amd64.deb
  build_rpm:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - attach_workspace:
          at: _build
      - run:
          command: |
            sudo apt update
            sudo apt install -y make alien curl
      - run:
          command: |
            make buildrpm
      - store_artifacts:
          path: _build/poplog-16.1-1.x86_64.rpm
          destination: poplog-16.1-1.x86_64.rpm
  build_appimage:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - attach_workspace:
          at: _build
      - run:
          command: |
            sudo apt update
            sudo apt install -y make curl
      - run:
          command:
            make buildappimage
      - store_artifacts:
          path: _build/Poplog-x86_64.AppImage
          destination: Poplog-x86_64.AppImage
  build_snap:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Get system info
          command: uname -a
      - attach_workspace:
          at: _build
      - run:
          command: |
            sudo apt update
            sudo apt install -y make curl snapd
            sudo snap install snapcraft --edge --classic
      - run:
          command:
            make buildsnap
      - store_artifacts:
          path: _build/dotsnap/poplog_16.0.1_amd64.snap
          destination: poplog_16.0.1_amd64.snap
workflows:
  version: 2
  mainflow:
    jobs:
      - one_line_install
      - build_tree
      - build_deb:
          requires:
            - build_tree
      - build_rpm:
          requires:
            - build_tree
      - build_appimage:
          requires:
            - build_tree
      - build_snap:
          requires:
            - build_tree
