# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          command: |
            make jumpstart-ubuntu
            make build
            sudo make install
      - run:
          command: |
            make _build/poplog_0.1-1_amd64.deb
            make _build/poplog-0.1-2.x86_64.rpm
            make _build/poplog-0.1.slp
      - run:
          command: |
            curl -LsS https://raw.githubusercontent.com/GetPoplog/Seed/main/GetPoplog.sh | sh
      - store_artifacts:
          path: _build/poplog_0.1-1_amd64.deb
          destination: poplog_0.1-1_amd64.deb
      - store_artifacts:
          path: _build/poplog-0.1-2.x86_64.rpm
          destination: poplog-0.1-2.x86_64.rpm
      - store_artifacts:
          path: _build/poplog-0.1.slp
          destination: poplog-0.1.slp
